### ISSUE TITLE
Reviewing Sharon's To-Do-list

### ISSUE THREAD

**Issue by Carshy** [sharon-odhiambo/TO-DO-LIST#9]
You did a great job implementing the project. Congratulations👏👏
However, we identified one issue, which would be great if you find some time and fix it.
* The clear completed feature clears all the tasks instead of removing only the checked tasks. Kindly fix it so that it can only clear the selected tasks.

**Comment by sharon-odhiambo** [comment]
-Hi @Carshy , Thanks for the suggestions. I have implemented it.
